# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@master
      - uses: c-hive/gha-yarn-cache@v1

      - name: Install node modules
        run: |
          yarn install
      # Runs a single command using the runners shell
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      # To run in Linux environments
      - name: Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Make Gradlew Executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android App Bundle
        run: |
          cd android && ./gradlew assembleRelease --no-daemon
      - name: Distribute app via Firebase App Distribution
        env:
          firebaseToken: 1//0gKi_2D9ufR7wCgYIARAAGBASNwF-L9IrJdU2FNXpO1ool_hKBm8CBnqCkVr1rMt3LNcyJ0ezWdS1CxRF93lS7tDM7Yv4Yt2Y1nw
          firebaseGroups: TechPulse
          firebaseAppId: 1:884301961169:android:8dd788398514769d6632f0
          notes: final prototype
        run: |
          yarn global add firebase-tools
          export PATH="$(yarn global bin):$PATH"
          firebase \
            appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app $firebaseAppId \
            --release-notes "$notes" \
            --groups "$firebaseGroups" \
            --token "$firebaseToken"
